// cnst_rom.v

// Generated using ACDS version 15.1 193

`timescale 1 ps / 1 ps
module cnst_rom (
		input  wire       address, //  rom_input.address
		input  wire       clock,   //           .clk
		output wire [7:0] q        // rom_output.dataout
	);

	cnst_rom_rom_1port_151_5e6juei rom_1port_0 (
		.address (address), //  rom_input.address
		.clock   (clock),   //           .clk
		.q       (q)        // rom_output.dataout
	);

endmodule
