// ff_bus1to16.v

// Generated using ACDS version 15.1 193

`timescale 1 ps / 1 ps
module ff_bus1to16 (
		input  wire [533:0] data,    //  fifo_input.datain
		input  wire         wrreq,   //            .wrreq
		input  wire         rdreq,   //            .rdreq
		input  wire         wrclk,   //            .wrclk
		input  wire         rdclk,   //            .rdclk
		input  wire         aclr,    //            .aclr
		output wire [533:0] q,       // fifo_output.dataout
		output wire [4:0]   wrusedw, //            .wrusedw
		output wire         rdempty, //            .rdempty
		output wire         wrfull   //            .wrfull
	);

	ff_bus1to16_fifo_151_4q2xupy fifo_0 (
		.data    (data),    //  fifo_input.datain
		.wrreq   (wrreq),   //            .wrreq
		.rdreq   (rdreq),   //            .rdreq
		.wrclk   (wrclk),   //            .wrclk
		.rdclk   (rdclk),   //            .rdclk
		.aclr    (aclr),    //            .aclr
		.q       (q),       // fifo_output.dataout
		.wrusedw (wrusedw), //            .wrusedw
		.rdempty (rdempty), //            .rdempty
		.wrfull  (wrfull)   //            .wrfull
	);

endmodule
